:icons: font

= Santiago Angel
Consultant/Pre-Sales Architect, Volante Technologies, Inc
santiagoangel@gmail.com

== Summary
Software architect with more than 10 years of experience in the financial, electric, education and public sectors with expertise in the areas of design, development and migration of applications with a focus on Java, web technologies, user interfaces and data processing. 

== Experience
=== Consultant/Pre-Sales Architect at Volante Technologies
*Mexico City (Mexico) · Full-time · Since June 2015*

Responsabilities: Architecture, consulting, design and support for projects at _HSBC Global Banking and Markets Mexico and Latin America_ and with clients in Mexico, United States and Colombia.
Responsible for the architecture of web services and UI for our product line _VolPay_(Foundation, Hub and Channel).

Technologies used: Java Enterprise Edition 6 & 7, JAX-RS, JAX-WS, JAXB, JPA, Oauth, JWT, Apache CXF, JBoss Keycloak, JBoss PicketLink, Apache DeltaSpike, Spring Security, Red Hat JBoss EAP, Red Hat JBoss Tools, Apache Camel, Red Hat JBoss Fuse, Netty, IBM MQ, Volante Technologies Designer, Unix Shell, Eclipse, IntelliJ IDEA, UML, Maven, HTML5, AngularJS, jQuery, Bootstrap, C3, D3, Grunt. 


=== Java Technical Lead at Grupo Financiero Interacciones online banking
*Mexico City (Mexico) · Fulltime · March 2015 - May 2015*

Responsabilities: Continuous improvement and implementation of key functionalities of the bank's security. Dynamic integration of authorization services for the business process protection. Creation of a security API design for backend consuming.

Technologies used: JAX-RS, JAX-WS, WS-Security, CXF, Oauth, JWT, SAML, Spring Security, Red Hat JBoss Data Grid, Red Hat JBoss EAP, Red Hat JBoss Tools. 


=== Senior Software Engineer at HSBC Global Banking and Markets
*Mexico City (Mexico) · Fulltime · August 2014 - March 2015*

Responsabilities: Solutions design for the Risk and Regulatory Reports area of Bank of Mexico. Financial data integration and process engineering to unify different data sources and channels through data buses and business intelligence software.

Achievements: Improvement in the report generation. Time and risk reduction associated with new projects.

Technologies used: IBM Rational Team Concert, Red Hat Enterprise Linux 5, Informix DB, Oracle DB, Oracle Weblogic, IBM Websphere Application Server 6 & 7, Spring, Apache Camel, Red Hat JBoss Fuse, Volante Technologies Designer, Oracle Data Integrator, Unix Shell, AWK, IBM Sterling Connect Direct, Informix 4GL, Control- M, Eclipse, Maven, Java Security(Jasypt, Bouncy Castle).

=== Senior Software Engineer at BBVA Bancomer online banking for businesses
*Mexico City (Mexico) · Fulltime · December 2013 - August 2014*

Responsabilities: Support in the front-end architecture design. Framework election that met corporative requirements. Proof of concept, demonstrations and beta versions development.

Achievements: Development time reduction through automated build solutions integration. Code testing. State-of-the-art technology balance uses with stable, secure and validated versions.

Technologies used: IBM Rational Architect, Eclipse, STS, HTML 5, Spring(MVC, AOP, Thymeleaf), Hibernate Validator, JQuery, AngularJS, IBM Websphere 6 & 7, Maven, SVN, REST Web services.


=== Senior Software Engineer at Grupo Posadas
*Mexico City (Mexico) · Fulltime · April 2013 - November 2013*

Responsabilities: Requirements analysis and project implementation. Support and development to all of the company's loyalty portals. Production troubleshooting. Migrating projects in a continuous integration environment.

Achievements: Faster response time to fix errors through that use shared code repositories. Improvement in new and existing developments due to the implementation of agile environments and working methods based on standards.

Technologies used: IBM Rational Architect, Java EE, JBoss Enterprise Application Platform, JBoss Enterprise Portal, JBoss Enterprise SOA Platform, Eclipse, STS, SSH, Maven, SVN, Bash shell, JBoss Developer Studio, Oracle SQL Developer, Java EE, HTML 5, Spring, JSF, EJBs, JQuery, Alfresco ECM, JBoss ESB, Jira, Jenkins. 


=== Software Engineer at BBVA Bancomer personal online banking
*Mexico City (Mexico) · Fulltime · July 2012 - April 2013*

Responsabilities: Design, development and testing for online banking (current and new version). Development of the login page (login) to integrate existing and new banks into a single model. Improvement and updating of applications. Automated generation of statistics and reports for user logs through bash scripts. Attention incidents in production, media analysis solutions to productive problems and reporting of business rules (BPW).

Achievements: Improved performance of the applications used in online banking. Web applications now meet current safety standards and HTML5. Automation of different processes.

Technologies used: Eclipse, STS, Bash shell, IBM Rational Architect, Java EE, HTML 5, Spring(MVC, security), JQuery, IBM Websphere 6 & 7, Apache Geronimo, Visual Age, SSH, Maven, SVN, Git, Jira, IBM MQ, LDAP, REST Web services, UNIX Daemons. 

=== Jr. Software Architect at National Polytechnic Institute/Federal Electricity Commission
*Mexico City (Mexico) · Fulltime · June 2007 - July 2012*


Responsabilities: Architecture design for the project. Sequence and class diagrams. Functional specification. Development of UI (Java Swing). Integration of geographic data (position of electrical equipment). Deployment of the electricity grid maps. Database modeling following the specification IEC CIM 61968. Migration and integration between databases (Informix and PostgreSQL). Application integration calculation for electrical networks programmed in Fortran and its conversion to JSON web services. Coordination of programmers and developers. Selection of software and hardware. Presentation of the project to CFE's managers.

Achievements: Creating innovative technology and world-class in the field of electrical engineering. Savings in project resources due to the usage of open software solutions. The implemented software can be scaled horizontally or vertically thanks to the raised modular architecture.

Technologies used: Enterprise Architect, Power Designer, Oracle SQL Developer, DB Visualizer, EnterpriseDB's PostgreSQL Advanced Server, Informix, JBoss Enterprise Application Platform, Spring, Hibernate, Eclipse, Netbeans, SSH, Maven, Git. 


=== Software Developer at Federal Electricity Commission Technological University
*Mexico City (Mexico) · Consultant · January 2010 - July 2010*

Administration, operationalization and technical support to the distance learning platform _Moodle_ used in the educational offer.  Platform monitoring. Interface customization.

=== Software Developer at Federal Electricity Commission
*Mexico City (Mexico) · Consultant · December 2009 - January 2010*

Graphical interfaces migration from GTK to Nokia Qt. Correction and adaptation of C code to C ++.

=== Software Developer at Secretariat of Public Education/National Polytechnic Institute
*Mexico City (Mexico) · Consultant · November 2008 - December 2009*

Administration, operationalization and technical support to the distance learning platform _Moodle_ used in the educational offer.  Platform monitoring. Interface customization.

=== Software Developer at ADEMSA
*Mexico City (Mexico) · Fulltime · October 2006 - January 2007*

Improving administration and billing system tailored for this company implemented in Java using Apache Tomcat as application server and MS SQL Server as a database.

=== Software Developer at Technoloy Solutions of Mexico
*Mexico City (Mexico) · Fulltime · September 2006 - December 2006*

Creation of an electronic billing system. Developed to measure, using advanced electronic signature and Solomon ERP. It was implemented in Java using JBoss as an application server and MS SQL Server as a database.

Software Document management for the National Insurance and Bonding Commission. I coordinated a team of programmers to make corrections and improvements to the development.


== Proyects
=== FEC - Banxico. Reporte de operaciones. October 2015 to date
Santiago Angel, Alicia Maya, Julio César Navarro Cabrera 

HSBC - Reporting of transactions involving amounts over $ 100,000 USD to Mexico’s central bank (Banxico) by the FEC protocol via TCP sockets using IBM MQ, Netty, Apache Camel and Volante Designer for transforming internal bank data to the format, channel encoding and serialization required by Banxico.

=== VolPay Hub June 2015 to date
Santiago Angel, David Lozano, Santiago Montesinos Padilla, José García 

VolPay Hub is a centralizing payment orchestration engine for the digital payments age. Through open, configurable adapters any payment type, from any source or channel can be acquired and processed by the system. VolPay Hub enables the rapid standardization of processes and workflows, applying business defined rules to control and manage the flow of payment transactions inside the organization from acquisition to delivery. The application is a configurable, centralized, digital payment process orchestration application. It simplifies the mechanism for on-boarding new payment flows and then enables the execution of the necessary technical and functional activities to successfully and efficiently complete the lifecycle of any payment transaction. http://www.volantetech.com/products/volpay/

=== Reportes Regulatorios - Garantías - Banco de México November 2014 to March 2015
HSBC - Compliance reports to Mexico’s central bank (Banxico) of stock market transactions with Volante Designer for transformation and integration of internal data and generation of documents & statistics.

=== Simulador del Sistema Eléctrico de Distribución de CFE June 2007 to June 2012
Santiago Angel, Ricardo Mota-Palomino, Miguel Jiménez Guzmán

This simulator allows the user to analyze and study future or historical conditions on the electrical behavior of the distribution network and take corrective or reactive actions. http://www.youtube.com/watch?v=pi6_lm8fYUw

== Education
*Bachelor of Science in Communications and Electronic Engineering with emphasis in Computing*

National Polytechnic Institute, School of Mechanic and Electric Engineering, Mexico · 2002 - 2007

== Certifications
Java EE 7 & AngularJS, New Circle Training, May 2014

Apache Cassandra Developer Training, DataStax, August 2013

Sun Certified Java Programmer, Global Knowledge, January 2010

Linux, ESIME IPN, January 2006

Java, ESIME IPN, October 2005

Computer Programer, Grupo CCEA, October 1996

English, Instituto Angloamericano, January 1995

== Skills
=== Languages
Spanish (native)

English (professional proficiency)

=== Web Development
HTML, AngularJS, jQuery, Bootstrap.

=== Programming Languages
Java, Javascript, C, C++, Bash, Fortran.

=== Databases
MySQL, SQL Server, Informix, Oracle, PostgreSQL, Apache Cassandra.

=== Operating Systems
Linux, Solaris, Mac OS X, Windows.

=== Others
Enterprise Architect, Power Designer, Oracle SQL Developer, DB Visualizer, EnterpriseDB's PostgreSQL Advanced Server, IBM Websphere Application Server 6-7-8.5 , JBoss Enterprise Application Platform 5-6, JBoss AS 7, JBoss Wildfly AS, Eclipse, Netbeans, Spring, JSF, EJBs, SSH, Maven, Git, Bash, AWK, Jira, IBM Rational Architect, IBM Rational Team Concert, Red Hat Enterprise Linux 5-6-7, Informix DB, Oracle DB, Oracle Weblogic 11, Oracle Data Integrator, Volante Technologies Designer, IBM Sterling Connect Direct, Informix 4GL, Control-M, JBoss Developer Studio, Intel Compiler Suite, Maven, Git, Moodle, MySQL, Apache HTTPd, PHP, GIMP, Qt Designer, Gtk Glade, Gcc, Cygwin, Visual Studio, Vi, Apache AB, rsync, Hibernate, JSP, Apache Tomcat, iText, Ibatis, Struts, Red Hat OpenShift, Docker, JBoss Enterprise Portal Platform, JBoss Enterprise SOA Platform, STS, Alfresco ECM, JBoss ESB, Java Security(Jasypt, Bouncy Castle), Jenkins, Apache Cassandra, JEE7, AngularJS, Apache Camel, Red Hat JBoss Fuse.
